# -*- coding: utf-8 -*-
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication,QFrame
from qfluentwidgets import BodyLabel, CardWidget, LineEdit, PushButton, SubtitleLabel, TitleLabel
from tabb1 import dz1
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CardWidget = CardWidget(Form)
        self.CardWidget.setMinimumSize(QtCore.QSize(20, 0))
        self.CardWidget.setObjectName("CardWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CardWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleLabel = TitleLabel(self.CardWidget)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.BodyLabel_6 = BodyLabel(self.CardWidget)
        self.BodyLabel_6.setObjectName("BodyLabel_6")
        self.gridLayout.addWidget(self.BodyLabel_6, 2, 2, 1, 1)
        self.BodyLabel = BodyLabel(self.CardWidget)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout.addWidget(self.BodyLabel, 0, 0, 1, 1)
        self.BodyLabel_2 = BodyLabel(self.CardWidget)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout.addWidget(self.BodyLabel_2, 0, 2, 1, 1)
        self.BodyLabel_4 = BodyLabel(self.CardWidget)
        self.BodyLabel_4.setText("")
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.gridLayout.addWidget(self.BodyLabel_4, 1, 2, 1, 1)
        self.BodyLabel_9 = BodyLabel(self.CardWidget)
        self.BodyLabel_9.setObjectName("BodyLabel_9")
        self.gridLayout.addWidget(self.BodyLabel_9, 3, 0, 1, 1)
        self.LineEdit_2 = LineEdit(self.CardWidget)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.gridLayout.addWidget(self.LineEdit_2, 1, 1, 1, 1)
        self.LineEdit_5 = LineEdit(self.CardWidget)
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.gridLayout.addWidget(self.LineEdit_5, 3, 1, 1, 1)
        self.LineEdit_3 = LineEdit(self.CardWidget)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.gridLayout.addWidget(self.LineEdit_3, 2, 1, 1, 1)
        self.BodyLabel_3 = BodyLabel(self.CardWidget)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.gridLayout.addWidget(self.BodyLabel_3, 1, 0, 1, 1)
        self.LineEdit = LineEdit(self.CardWidget)
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout.addWidget(self.LineEdit, 0, 1, 1, 1)
        self.BodyLabel_5 = BodyLabel(self.CardWidget)
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.gridLayout.addWidget(self.BodyLabel_5, 2, 0, 1, 1)
        self.BodyLabel_10 = BodyLabel(self.CardWidget)
        self.BodyLabel_10.setText("")
        self.BodyLabel_10.setObjectName("BodyLabel_10")
        self.gridLayout.addWidget(self.BodyLabel_10, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PushButton = PushButton(self.CardWidget)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout_2.addWidget(self.PushButton)
        self.PushButton_2 = PushButton(self.CardWidget)
        self.PushButton_2.setObjectName("PushButton_2")
        self.horizontalLayout_2.addWidget(self.PushButton_2)
        self.PushButton_3 = PushButton(self.CardWidget)
        self.PushButton_3.setObjectName("PushButton_3")
        self.horizontalLayout_2.addWidget(self.PushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.CardWidget_2 = CardWidget(self.CardWidget)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.CardWidget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SubtitleLabel = SubtitleLabel(self.CardWidget_2)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.horizontalLayout_4.addWidget(self.SubtitleLabel)
        self.LineEdit_6 = LineEdit(self.CardWidget_2)
        self.LineEdit_6.setMinimumSize(QtCore.QSize(20, 0))
        self.LineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LineEdit_6.setObjectName("LineEdit_6")
        self.horizontalLayout_4.addWidget(self.LineEdit_6)
        self.verticalLayout.addWidget(self.CardWidget_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout.setStretch(4, 1)
        self.horizontalLayout.addWidget(self.CardWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleLabel.setText(_translate("Form", "模型一-四因素"))
        self.BodyLabel_6.setText(_translate("Form", "%"))
        self.BodyLabel.setText(_translate("Form", "土层埋深"))
        self.BodyLabel_2.setText(_translate("Form", "m"))
        self.BodyLabel_9.setText(_translate("Form", "循环剪应力比"))
        self.BodyLabel_3.setText(_translate("Form", "修正标贯基数"))
        self.BodyLabel_5.setText(_translate("Form", "细粒含量"))
        self.PushButton.setText(_translate("Form", "清除结果"))
        self.PushButton_2.setText(_translate("Form", "快速计算"))
        self.PushButton_3.setText(_translate("Form", "全部清除"))
        self.SubtitleLabel.setText(_translate("Form", "概率"))

class New_tab1(QFrame):

    def __init__(self):
        super(New_tab1, self).__init__()
        self.ui = Ui_Form()
        self.ui.setupUi(self)
        self.ui.PushButton.clicked.connect(self.clear_results)
        self.ui.PushButton_3.clicked.connect(self.clear)
        self.ui.PushButton_2.clicked.connect(self.dz)

    def dz(self):
        x1 = float(self.ui.LineEdit.text())
        x2 = float(self.ui.LineEdit_2.text())
        x3 = float(self.ui.LineEdit_3.text())
        x4 = float(self.ui.LineEdit_5.text())
        res = dz1.dz11(x1,x2,x3,x4)
        self.ui.LineEdit_6.setText(str(res))
    def clear_results(self):
        # 清空输入字段
        self.ui.LineEdit_6.clear()

    def clear(self):
        self.ui.LineEdit.clear()
        self.ui.LineEdit_2.clear()
        self.ui.LineEdit_3.clear()
        self.ui.LineEdit_5.clear()
        self.ui.LineEdit_6.clear()

if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = New_tab1()
    w.show()

    app.exec()